# -- FILE: behave.ini
# Define ALIAS for HtmlFormatter.

#[behave.formatters]
#html = behave_html_formatter:HTMLFormatter
#lang = es

[behave]
format=allure_behave.formatter:AllureFormatter
outfiles=allure-results
lang = es